### ISSUE TITLE
Use of Number(id) @ https://fullstackopen.com/en/part7/react_router returns an error.

### ISSUE THREAD

**Issue by AM-thedev** [fullstack-hy2020/fullstack-hy2020.github.io#1483] opened 2021-09-05 08:02 UTC
For part 7, in the chapter 'React Router' the suggested code is given:
`const note = match 
  ? notes.find(note => note.id === Number(match.params.id))
  : null`

However, when I tried using it in my assignment work, it caused the app to crash.  Removing `Number()` as in: 
`const note = match 
  ? notes.find(note => note.id === match.params.id)
  : null`
Fixed the crash.  If possible, could someone else chime in on whether they had the same issue?  The issue replicates on my end.

**Comment by akirataguchi115** [comment] 2022-01-15 10:05
Using [this](https://github.com/fullstack-hy/misc/blob/main/router-app-v2.js) as a template I couldn't reproduce the issue you've encountered. However I do recall having the same issue with my own assignment. This was due to the id not being a Number so I also removed the Number prefix.

Please close this issue if you think the problem is solved :octocat:

**Closed** 2022-02-06 09:24 UTC
