### ISSUE TITLE
Add file paths to code snippets

### ISSUE THREAD

**Issue by Aarons9090** [fullstack-hy2020/fullstack-hy2020.github.io#2040] opened 2022-06-02 12:12 UTC
Adding file paths to code snippets in the study material would make following the examples easier.

Example
![näyttökuva](https://user-images.githubusercontent.com/83041434/171626500-7fcbfbd3-0d05-4dfa-bf64-8527909bba07.png)

**Comment by mluukkai** [comment] 2024-09-02 18:03
duplicate of https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/issues/478

**Closed as completed by mluukkai** 2024-09-02 18:03 UTC
